version: '3'
services:
  resume-app:
    container_name: resume-app
    build: .
    image: resume-creator:latest
    ports:
      - "3000:13000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules